# Generated by Django 4.2.7 on 2024-01-12 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clapStationWebsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_posts',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
